name: 2 - Deploy Application to UAT

# Trigger ONLY when code successfully lands in the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to trigger a manual deployment

jobs:
  deploy-to-test:
    name: Apply Changes to Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger ServiceNow CI/CD API
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: ${{ secrets.NOWUSERNAME }}
          nowPassword: ${{ secrets.NOWPASSWORD }}
          nowInstallInstance: ${{ secrets.NOWINSTALLINSTANCE }}
          # The sys_id below is the ID of your custom Global Application record
        with:
          app_sys_id: ${{ secrets.APP_SYS_ID }}
