name: Deploy to PDI-Test

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Apply Changes to Test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ServiceNow CI/CD API
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: ${{ secrets.NOWUSERNAME }}
          nowPassword: ${{ secrets.NOWPASSWORD }}
          nowSourceInstance: ${{ secrets.NOWINSTALLINSTANCE }}
          appSysID: "7eb34c4f83c10b10103cba29feaad30c"
          appScope: "GlobalCatalogReceiver"
